hidden_paths:
  - .*
options:
  colours:
    red: Rouge
    blue: Bleu
    white: Blanc
  numbers:
    - 0
    - 1
    - 2
    - 3
    - 10
  pastas:
    spa: Spaghetti
    pen: Penne
    rot: Rotini
    bar: Barbina
    cap: Capellini
    fus: Fusilli
