options:
  colours:
    red: Rouge
    blue: Bleu
    white: Blanc
  numbers:
    - 0
    - 1
    - 2
    - 3
    - 10
  pastas:
    - Spaghetti
    - Penne
    - Rotini
    - Barbina
    - Capellini
    - Fusilli
