title: Your awesome title
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.\r\n"
baseurl: ''
url: http://yourdomain.com
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
exclude:
- Makefile
- makefile
date: 2016-07-28
stuff_date: ''
colours:
  red: Rouge
  blue: Bleu
  white: Blanc
numbers:
  - 0
  - 1
  - 2
  - 3
  - 10
